### ISSUE TITLE
[냉장고 음식] CRUD 개발

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_SERVER#13]
## 💎 Outline
냉장고 음식 추가 CRUD API를 개발합니다.

## 🎯 To-Do
- [ ] API 문서 작성
- [ ] DB 확정
- [ ] [POST] 냉장고 음식 추가(List)
- [ ] [PUT] 냉장고 음식 수정
- [ ] [GET] 유저의 냉장고 음식 반환
- [ ] [GET] (유저 냉장고 음식 반환 시) 남은 디데이 계산 + 디데이별 오름차순
- [ ] [GET] 유저 냉장고 음식 반환 시 '냉동/냉장' + '육류/채소/유제품' 구분
