### ISSUE TITLE
[식재료 거래] CRUD 개발

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_SERVER#15]
## 💎 Outline
식재료 거래에 필요한 전반적인 API를 개발합니다.

## 🎯 To-Do
- [x] [GET] 위치기반 식재료 거래 목록 반환 API
- [x] [POST] 식재료 거래 등록 API
- [x] [PUT] 식재료 거래 완료 API
- [x] [POST] 식재료 거래 요청 API
- [x] [DELETE] 식재료 거래 삭제 API(사용자가 등록한 거래)
- [x] [DELETE] 식재료 거래 취소 API(사용자가 요청한 거래)
- [x] [GET] 사용자별 거래 조회 API
- [x] [GET] 거래 단건 조회 API
- [x] [GET] 식재료 거래 목록 조회 API

**Comment by yhjune** [comment]
plus code
https://github.com/google/open-location-code

The initial top level grid lines are spaced at 20° intervals along longitude and latitude. Each row and column is then sequentially labelled with one of the 20 Plus Code alphanumeric characters allowing every cell to be easily referenced (for example, 9C).

Zooming into an individual cell, the cell is further divided into a 20x20 grid with each column and row being sequentially labelled with one of the 20 Plus Code alphanumeric characters. This process is then repeated allowing for a zoomed in Plus Code to be created. In our example, the cell reference 9C5M8QQ7+V8R is the Plus Code for that cell.

The technology is designed to produce codes that can be used as a replacement for street addresses, especially in places where buildings aren't numbered or streets aren't named.

Codes are made up of a sequence of digits chosen from a set of 20. The digits in the code alternate between latitude and longitude. The first four digits describe a one degree latitude by one degree longitude area, aligned on degrees. Adding two further digits to the code, reduces the area to 1/20th of a degree by 1/20th of a degree within the previous area. And so on - each pair of digits reduces the area to 1/400th of the previous area.

There will be locations where a 10-digit code is not sufficiently precise, but refining it by a factor of 20 is i) unnecessarily precise and ii) requires extending the code by two digits. Instead, after 10 digits, the area is divided into a 4x5 grid and a single digit used to identify the grid square. A single grid refinement step reduces the area to approximately 3.5x2.8 meters.

**Comment by yhjune** [comment]
**Why not use latitude and longitude?**

One answer is that if latitude and longitude were a practical solution, people would already be using them. The problem with latitude and longitude is that they are two numbers, possibly signed, with a lot of digits, and the order is important.

But latitude and longitude, and many other systems such as MGRS, geocodes, etc, also have the problem that they do not look like addresses. We all know what an address looks like - a collection of references from less detailed to more detailed, typically: country, state, city, street, and house. This hierarchy is important since it makes it easy to determine if something is near or far without having to understand the whole thing. You can tell if it's in a different city without having to know the street name.

**Comment by yhjune** [comment]
개발 순서 
[POST] 식재료 거래 등록 API
[DELETE] 식재료 거래 삭제 API(사용자가 등록한 거래)
[GET] 위치기반 식재료 거래 목록 반환 API

 [GET] 사용자별 거래 조회 API

 [POST] 식재료 거래 요청 API
 [DELETE] 식재료 거래 취소 API(사용자가 요청한 거래)
 [PUT] 식재료 거래 완료 API

**Comment by yhjune** [comment]
[GET] 거래 단건 조회 API
[GET] 식재료 거래 목록 조회 API 
할일 추가
