### ISSUE TITLE
[배포] Docker, Github Actioin, CI/CD, EC2

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_SERVER#31]
## 💎 Outline
배포 계획을 단계별로 작성합니다.

## 🎯 To-Do
- [x] 🐳  도커로 빌드하여 실행
- [x] ⏯️  Github Actions / Test Code 자동 실행
- [x] ⏯️  Github Actions / S3 연동
- [x] ⏯️ 🐳 Github Actions / ECR & ECS로 서버 배포(시도 후 안되면 EC2 쓰기)
