### ISSUE TITLE
[FEATURE] 식재료 관리 API

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_SERVER#38]
## 💎 Outline
식재료 관련 CRUD 및 소비 상태를 관리하는 API를 개발합니다.

## 🎯 To-Do
- [x] **SETTING** 쿼리 최적화를 위한 queryDSL 적용
- [x] **ENTITY** 변경된 컬럼 추가
- [x] **POST** 식재료 삭제 시 [사용 완료 - CONSUMED] [음식물 쓰레기 - WASTED]로 값 변경되도록 수정
- [x] **POST** 식재료 생성 시 status 값 기본으로 [상태 없음 - NONE] 설정되도록 변경
