### ISSUE TITLE
[FEATURE] 식재료 사용 Tracking API

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_SERVER#39]
## 💎 Outline
식재료 사용 현황을 Tracking하는 API를 작성합니다.

## 🎯 To-Do
- [x] **QUERY** 월별로 사용자가 등록한 식재료의 개수
- [x] **QUERY** 월별로 사용자가 모두 사용한 식재료의 개수
- [x] **QUERY** 월별로 사용자가 음식물 쓰레기로 배출한 식재료의 개수
- [ ] **QUERY** 모든 사용자의 등록 / 사용 / 버린 식재료의 개수
- [ ] **QUERY** 월별로 사용자가 음식물 쓰레기로 배출한 식재료의 개수 - 5개월 전~현재
- [x] **GET** 위의 결과값을 하나의 response에 담아 return

**Comment by sunnyineverywhere** [comment]
## 🔥 추가 수정사항
> 삭제된 냉장고 그룹에서 사용한 음식물 쓰레기가 통계에 집계되지 않는 에러가 발생할 가능성이 있어 아래와 같이 변경 예정
- [x] 냉장고 그룹 삭제할 때 쿼리에서 DELETE하는 대신 `fridge` 사용 상태를 `STOPPED`로 변경
- [x] 냉장고 그룹에서 멤버를 _제거 || 탈퇴_ 할 때 `family`의 `role`을 `REMOVED`로 변경

**Comment by sunnyineverywhere** [comment]
## 💡 Base SQL Query
```sql
select count(food.food_id)
from food
left join fridge on food.fridge_id = fridge.fridge_id
left join family on fridge.fridge_id = family.fridge_id 
where family.member_id = 1
```
