### ISSUE TITLE
S3 버킷 통해 이미지 업로드

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_SERVER#4]
# TO-DOs
- [x] S3 버켓 생성 & 세팅
- [x] image 테이블에 이미지 url, 파일명 insert

# Goals
- [x] 다른 테이블에서 조회 후 http response로 반환 시 이미지 확인 가능

# Etc
- feature/image 브랜치에서 작업

**Comment by yhjune** [comment]
### postman 요청시 401 unauthorized 에러가 계속 납니다

 원래는 403 Forbidden Error로 S3 버킷 설정 문제인 줄 알았습니다. 
 근데 get/put/deleteObject 열어두고 다시 요청하니까 401 이 뜸
 S3 엑세스 키 문제인가 싶어서 해당 부분도 확인해 봤는데 이상 없었음

**시도해본 해결 방안** 
https://community.postman.com/t/im-getting-401-unauthorized-error/38820
- Basic Auth로 Security 패스워드 헤더로 보내줬음 => 해결 안됨
- API-KEY : 역시 안됨

**예상 문제점**
S3 버킷 설정...?

***

### 해결
Spring Config 문제였음

**Comment by yhjune** [comment]
s3 연동 중 Endpoint does not contain a valid host name: null => 지역 버킷이름도 다 맞는데 왜 틀리는지 이유를 알 수 없었음
전체 종료 후 다시 하니까 되는데 이유가...?
