### ISSUE TITLE
[FEATURE] 냉장고 멤버 및 유저 프로필 관리

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_SERVER#40]
## 💎 Outline
냉장고 멤버 내 멤버들을 관리하는 api를 개발합니다.
유저 프로필을 업데이트할 수 있는 api를 개발합니다.

## 🎯 To-Do
- [x] **PUT** 유저 닉네임 변경
- [x] **POST** 유저에게 온 초대를 수락하는 api
- [x] **GET** 유저에게 온 초대를 모두 보여주는 api
