### ISSUE TITLE
[FEATURE] 냉장고 관리 API

### ISSUE THREAD

**Issue by sunnyineverywhere** [CAPSTONE369/369_SERVER#41]
## 💎 Outline
냉장고 멤버 및 상태를 관리하는 api

## 🎯 To-Do
- [x] **DELETE** 냉장고 멤버 삭제 api
- [x] **DELETE** 냉장고 탈퇴 api
- [x] **DELETE** 유저가 냉장고를 OWNER일 때 냉장고를 삭제할 수 있는 api
- [x] **GET** 유저가 소속된 모든 냉장고를 return
